FROM alpine:3.16

ENV JAVA_HOME /opt/java/openjdk
ENV PATH $PATH:$JAVA_HOME/bin

COPY ./install-temurin-jdk.sh /tmp/install-temurin-jdk.sh
COPY ./install-maven.sh /tmp/install-maven.sh
COPY ./install-spring-cli.sh /tmp/install-spring-cli.sh

RUN apk --no-cache update \
    && apk --no-cache upgrade \
    # curl needed to download files
    # bash is required by spring-cli
    && apk add --no-cache curl bash \
    && ash /tmp/install-temurin-jdk.sh \
    && ash /tmp/install-maven.sh \
    && ash /tmp/install-spring-cli.sh \
    && rm /tmp/install-temurin-jdk.sh /tmp/install-maven.sh /tmp/install-spring-cli.sh

# ENV MAVEN_HOME /usr/share/maven
# ENV MAVEN_CONFIG "/root/.m2"

CMD ["ash"]

